baseURL = "https://virtual.github.io/nanowrimo/"
title = "NaNoWriMo"
languageCode = "en-us"
themesDir = "themes"
theme = "hugo-serif-theme" 

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-nano.svg"
    standard  = "images/logo-nano.svg"
    alt = "NaNoWriMo - A planning reference"

  [params.homepage_meta_tags]
    meta_description = "A planning reference for NaNoWriMo"
    meta_og_title = "NaNoWriMo Template"
    meta_og_type = "website"
    meta_og_url = "http://virtual.github.io/nanowrimo/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "A planning reference for NaNoWriMo"
    meta_twitter_card = "summary"
    meta_twitter_site = "@satinflame"
    meta_twitter_creator = "@satinflame"

[menu]
  # Main Menu
 

  [[menu.main]]
      name = "Characters"
      url = "/characters/"
      weight = 2


  [[menu.main]]
      name = "Beatsheet"
      url = "/beatsheet/"
      weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
 